name: RandomLootChest
author: Herzchen
authors: [bottomdumber, RestrictedPower]
version: 3.3.0
api-version: 1.13
main: me.Herzchen.RandomLootChest.Main
softdepend: [Multiverse-Core]

permissions:
  randomlootchest.*:
    description: Gives access to all RandomLootChest commands
    children:
      randomlootchest.general: true
      randomlootchest.additem: true
      randomlootchest.fixedchest: true
      randomlootchest.delall: true
      randomlootchest.killall: true
      randomlootchest.togglebreak: true
      randomlootchest.forcespawn: true
      randomlootchest.rndtime: true
      randomlootchest.wand: true
      randomlootchest.set: true
      randomlootchest.unset: true
      randomlootchest.chesttypes: true
      randomlootchest.resettimer: true
      randomlootchest.reload: true
      randomlootchest.regions: true
      randomlootchest.spawn: true
      randomlootchest.spawnregion: true
      randomlootchest.loottable: true
      randomlootchest.command.wand: true
      randomlootchest.command.set: true
      randomlootchest.command.unset: true

  randomlootchest.general:
    description: Access to general commands
  randomlootchest.additem:
    description: Access to additem command
  randomlootchest.fixedchest:
    description: Access to add/del chest commands
  randomlootchest.delall:
    description: Access to delall command
  randomlootchest.killall:
    description: Access to killall command
  randomlootchest.togglebreak:
    description: Access to togglebreak command
  randomlootchest.forcespawn:
    description: Access to forcespawn command
  randomlootchest.rndtime:
    description: Access to rndtime command
  randomlootchest.wand:
    description: Access to use wand command
  randomlootchest.set:
    description: Access to set command
  randomlootchest.unset:
    description: Access to unset command
  randomlootchest.chesttypes:
    description: Access to chesttypes command
  randomlootchest.resettimer:
    description: Access to resettimer command
  randomlootchest.reload:
    description: Access to reload command
  randomlootchest.regions:
    description: Access to regions command
  randomlootchest.spawn:
    description: Access to spawn command
  randomlootchest.spawnregion:
    description: Access to spawnregion command
  randomlootchest.loottable:
    description: Access to loottable command
  randomlootchest.command.wand:
    description: Access to use wand command
  randomlootchest.command.set:
    description: Access to set command
  randomlootchest.command.unset:
    description: Access to unset command

commands:
  rlc:
    description: Main command for RandomLootChest
    aliases: [randomlootchest]